### PR TITLE
Add option to switch to quickrun buffer

### PR DESCRIPTION
**Pull request by marsam**
Hi:
I've added an option to only display quickrun buffer.

Thanks in advance.

### CODE REVIEW

**Comment by syohex** [comment]
Thanks for suggestion.
This change causes issue when recentering window.

I fixed the issue and rename flag variable name at #52. Please check #52.

**Comment by marsam** [comment]
Cool! that is better than my patch :+1:

**Comment by syohex** [comment]
@marsam Thanks for checking. I have merged #52.
Please report me if you have any problems.

**Comment by marsam** [comment]
thanks!

**Pull request closed without merging**
